version: "3.9"
services:
  # First servise
  nginx:
    container_name: con_nginx
    ##image: nginx:1.21
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    volumes: 
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - wordpress
    networks: 
      - mynetwork

  # Second servise
  db:
    container_name: con_db
    build: ./requirements/mariadb
    image: db
    volumes:
    - db_data:/var/lib/mysql
    - ./requirements/mariadb/conf/my.cnf:/etc/mysql/my.cnf
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    networks:
    - mynetwork
    
  wordpress:
    container_name: con_wordpress
    #image: wordpress:php7.4-fpm-alpine
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    depends_on:
      - db
    volumes: 
    - wordpress_data:/var/www/html
    - ./requirements/wordpress/conf/wp-config.php:/var/www/html/wp-config.php
    networks:
    - mynetwork

volumes: 
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eternity/data/wordpress_data
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eternity/data/db_data
networks:
  mynetwork:
    name: mynetwork
    driver: bridge