version: "3.9"

services:
    # First servise
    nginx:
        #build: /srcs/requirements/nginx/Dockerfile
        image: nginx:1.21
        #environment: 
        ports:
            - "80:80"
            - "443:443"
        environment: 
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
        volumes: 
            - wordpress_data:/var/www/html
        networks: 
            - wpsite
        tty: true
    # Second servise
    db:
        #build: /srcs/requirements/mariadb
        image: mariadb:10
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        #ports:
         #   - "3306:9000"
        environment: 
            MARIADB_ROOT_PASSWORD: 123
            MARIADB_DATABASE: wordpress
            MARIADB_USER: wordpress
            MARIADB_PASSWORD: wordpress
        networks:
            - wpsite
    wordpress:
        depends_on: 
            - db
        build: ./requirements/wordpress
        #image: wordpress:5.7
        restart: always
        ports:
            - "9000:80"
        volumes: 
            - wordpress_data:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORRPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        depends_on: 
            - nginx
        networks:
            - wpsite
        tty: true


volumes: 
    wordpress_data:
    db_data:
networks:
    wpsite: