version: "3.9"

services:
  # First servise
  nginx:
    container_name: con_nginx
    build: ./requirements/nginx
    image: obr_nginx
    #image: nginx:1.21
    ports:
      - 80:80
      - 443:443
    volumes: 
      - wordpress_data:/var/www/html
    restart: always
    networks: 
      - mynetwork
    depends_on: 
      - wordpress

  # Second servise
  db:
    container_name: con_db
    build: ./requirements/mariadb
    image: obr_db
    #image: mariadb:10
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    #ports:
    #   - "3306:9000"
    environment: 
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    networks:
    - mynetwork
    

  wordpress:
    container_name: con_wordpress
    build: ./requirements/wordpress
    image: obr_wordpress
    #build:
    #context: ./requirements/wordpress
    #image: wordpress:5.7
    restart: always
    #ports:
    #- "9000:80"
    volumes: 
    - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORRPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on: 
    - db
    networks:
    - mynetwork

volumes: 
  wordpress_data:
  db_data:
networks:
  mynetwork: