version: "3.9"
services:
  # First servise
  nginx:
    container_name: con_nginx
    build: 
      context: ./requirements/nginx
      args: 
        - CERT=/etc/ssl/certs/nginx-selfsigned.crt
        - CERT_KEY=/etc/ssl/private/nginx-selfsigned.key
    image: nginx
    env_file:
      - .env
    ports:
      - 443:443
    volumes: 
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - wordpress
    networks: 
      - mynetwork

  # Second servise
  db:
    container_name: con_db
    build: ./requirements/mariadb
    image: db
    env_file:
      - .env
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    networks:
    - mynetwork
    
  wordpress:
    container_name: con_wordpress
    build:
      context: ./requirements/wordpress
      args: 
        - DB_PASSWORD=${DB_PASSWORD}
    image: wordpress
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    volumes: 
    - wordpress_data:/var/www/html
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    networks:
    - mynetwork

volumes: 
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rmerrie/data/wordpress_data
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rmerrie/data/db_data
networks:
  mynetwork:
    name: mynetwork
    driver: bridge