version: "3.9"
services:
  # First servise
  nginx:
    container_name: con_nginx
    ##image: nginx:1.21
    build: ./requirements/nginx
    image: nginx
    env_file:
      - .env
    ports:
      - 443:443
    volumes: 
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - wordpress
    networks: 
      - mynetwork
    environment: 
      DOMAIN_NAME: ${DOMAIN_NAME}
      CERT: ${CERT}
      CERT_KEY: ${CERT_KEY}

  # Second servise
  db:
    container_name: con_db
    build: ./requirements/mariadb
    image: db
    env_file:
      - .env
    volumes:
    - db_data:/var/lib/mysql
    - ./requirements/mariadb/conf/my.cnf:/etc/mysql/my.cnf
    restart: always
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
    - mynetwork
    
  wordpress:
    container_name: con_wordpress
    #image: wordpress:php7.4-fpm-alpine
    build: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    volumes: 
    - wordpress_data:/var/www/html
    ##- ./requirements/wordpress/conf/wp-config.php:/var/www/html/wp-config.php
    environment:
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    networks:
    - mynetwork

volumes: 
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eternity/data/wordpress_data
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eternity/data/db_data
networks:
  mynetwork:
    name: mynetwork
    driver: bridge