#!/user/bin/env bash
# Стартуем mysql
#mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '123';"
#mysql -e "FLUSH PRIVILEGES;"
service mysql start
mysql -u root --skip-password -e "CREATE DATABASE IF NOT EXISTS ${DB_DATABASE};"
mysql -u root --skip-password -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';"
mysql -u root --skip-password -e "GRANT ALL PRIVILEGES ON *.* TO '${DB_USER}'@'%';"
mysql -u root --skip-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '123';"
mysql -u root --skip-password -e "FLUSH PRIVILEGES;"
service mysql stop
#exec bash
exec mysqld
#ALTER USER 'root'@'localhost' IDENTIFIED BY '12345';